# Generated by Django 4.2 on 2023-08-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
