# Generated by Django 4.2 on 2023-08-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='beginner',
            field=models.BooleanField(default=False),
        ),
    ]
