# Generated by Django 4.1 on 2022-10-20 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.TextField()),
                ('name', models.TextField()),
                ('rated', models.IntegerField(default=True)),
                ('slug', models.TextField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField()),
                ('spread_cap', models.IntegerField(blank=True, null=True)),
                ('pairing_system', models.CharField(choices=[['ROUND_ROBIN', 'Round Robin'], ['SWISS', 'Swiss'], ['KOTH', 'KOTH'], ['RANDOM', 'Random'], ['MANUAL', 'Manual']], max_length=16)),
                ('repeats', models.IntegerField(default=0)),
                ('based_on', models.IntegerField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('played', models.IntegerField(default=0, null=True)),
                ('game_wins', models.FloatField(default=0, null=True)),
                ('round_wins', models.FloatField(default=0, null=True)),
                ('spread', models.IntegerField(default=0, null=True)),
                ('position', models.IntegerField(default=0, null=True)),
                ('offed', models.IntegerField(default=0, null=True)),
                ('seed', models.IntegerField(default=0, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournament.tournament')),
            ],
        ),
    ]
