# Generated by Django 4.1.3 on 2023-01-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('played', models.IntegerField(default=0, null=True)),
                ('game_wins', models.FloatField(default=0, null=True)),
                ('round_wins', models.FloatField(default=0, null=True)),
                ('spread', models.IntegerField(default=0, null=True)),
                ('position', models.IntegerField(default=0, null=True)),
                ('offed', models.IntegerField(default=0, null=True)),
                ('seed', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.TextField()),
                ('name', models.TextField()),
                ('rated', models.IntegerField(default=True)),
                ('slug', models.TextField(blank=True, unique=True)),
                ('team_size', models.IntegerField(blank=True, null=True)),
                ('entry_mode', models.CharField(choices=[('T', 'By Team'), ('P', 'By Player')], default='T', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField()),
                ('spread_cap', models.IntegerField(blank=True, null=True)),
                ('pairing_system', models.CharField(choices=[['ROUND_ROBIN', 'Round Robin'], ['SWISS', 'Swiss'], ['KOTH', 'KOTH'], ['RANDOM', 'Random'], ['MANUAL', 'Manual']], max_length=16)),
                ('repeats', models.IntegerField(default=0)),
                ('based_on', models.IntegerField(blank=True, null=True)),
                ('paired', models.BooleanField(default=False)),
                ('num_rounds', models.IntegerField()),
                ('team_size', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('wins', models.FloatField()),
                ('spread', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournament.participant')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournament.tournament'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_won', models.IntegerField(blank=True, null=True)),
                ('score1', models.IntegerField(blank=True, null=True)),
                ('score2', models.IntegerField(blank=True, null=True)),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p1', to='tournament.participant')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p2', to='tournament.participant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='tournament.tournamentround')),
                ('starting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='starting', to='tournament.participant')),
            ],
            options={
                'unique_together': {('round', 'p1', 'p2')},
            },
        ),
        migrations.CreateModel(
            name='BoardResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.IntegerField()),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournament.tournamentround')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team1', to='tournament.participant')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team2', to='tournament.participant')),
            ],
            options={
                'unique_together': {('round', 'team1', 'team2', 'board')},
            },
        ),
    ]
