# Generated by Django 4.1.3 on 2023-01-29 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentround',
            name='num_rounds',
        ),
        migrations.RemoveField(
            model_name='tournamentround',
            name='team_size',
        ),
    ]
