# Generated by Django 4.1.3 on 2023-01-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_tournamentround_num_rounds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='num_rounds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
