# Generated by Django 4.1 on 2022-10-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_team_size_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentround',
            name='paired',
            field=models.BooleanField(default=False),
        ),
    ]
