# Generated by Django 4.1.3 on 2023-01-25 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournamentround_num_rounds_tournamentround_team_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='entry_mode',
            field=models.CharField(choices=[('T', 'By Team'), ('P', 'By Player')], default='T', max_length=1),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournament.participant')),
            ],
        ),
        migrations.CreateModel(
            name='BoardResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.IntegerField()),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournament.tournamentround')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team1', to='tournament.participant')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team2', to='tournament.participant')),
            ],
            options={
                'unique_together': {('round', 'team1', 'team2', 'board')},
            },
        ),
    ]
