# Generated by Django 4.1.5 on 2023-02-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_director'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tournamentround',
            constraint=models.CheckConstraint(check=models.Q(('based_on__lt', models.F('round_no'))), name='based_on_check'),
        ),
    ]
