# Generated by Django 4.1.5 on 2023-02-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournamentround_based_on_check'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(check=models.Q(('game_wins__gte', 0)), name='wins_check'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(check=models.Q(('round_wins__gte', 0)), name='round_win_check'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(check=models.Q(('p1_id', models.F('p2_id'))), name='p1p2_check'),
        ),
        migrations.AddConstraint(
            model_name='tournamentround',
            constraint=models.CheckConstraint(check=models.Q(('round_no__gt', 0)), name='round_no_check'),
        ),
    ]
