# Generated by Django 4.1.3 on 2023-01-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_alter_result_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='margin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='wins',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
