# Generated by Django 4.1.3 on 2023-01-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_teammember_margin_teammember_wins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='margin',
            new_name='spread',
        ),
    ]
