# Generated by Django 4.1.5 on 2023-02-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_remove_result_p1p2_check_result_p1p2_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='position',
        ),
    ]
