# Generated by Django 4.1.5 on 2023-02-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_remove_participant_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('name', 'tournament')},
        ),
    ]
