# Generated by Django 4.1.7 on 2023-02-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_boardresult_t1t2_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardresult',
            name='score1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardresult',
            name='score2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
