# Generated by Django 4.1.7 on 2023-04-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_alter_result_games_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='seed',
            field=models.IntegerField(default=0),
        ),
    ]
