# Generated by Django 4.1.7 on 2023-04-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_participant_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='seed',
            field=models.IntegerField(),
        ),
    ]
