# Generated by Django 4.1.7 on 2023-04-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_alter_participant_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='white',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='entry_mode',
            field=models.CharField(choices=[('T', 'By Team'), ('S', 'Individual Tournament'), ('P', 'By Player')], default='T', max_length=1),
        ),
    ]
