# Generated by Django 4.1.7 on 2023-04-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_participant_white_alter_tournament_entry_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
