# Generated by Django 4.2 on 2023-06-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_alter_result_p1_alter_result_p2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
