# Generated by Django 4.2 on 2023-06-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0021_alter_tournament_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='private',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
