# Generated by Django 4.2 on 2023-06-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0022_alter_tournament_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='entry_mode',
            field=models.CharField(choices=[('T', 'By Team'), ('S', 'Individual Tournament'), ('P', 'By Player')], max_length=1),
        ),
    ]
