# Generated by Django 4.2 on 2023-07-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0025_alter_tournamentround_pairing_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='round_robin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
