# Generated by Django 4.2 on 2023-08-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0028_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
