# Generated by Django 4.2 on 2023-08-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0029_tournament_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='venue',
            field=models.CharField(blank=True, default='To be notified', max_length=100),
        ),
    ]
