# Generated by Django 4.2 on 2023-09-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0033_alter_participant_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='approval',
            field=models.CharField(choices=[('V', 'Verified'), ('R', 'Verficiation Failed'), ('P', 'Pending Verification'), ('U', 'Unpaid')], default='U', max_length=1),
        ),
    ]
