# Generated by Django 4.2 on 2023-09-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0035_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='payment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
