# Generated by Django 4.2 on 2023-09-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0037_alter_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fee',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
