# Generated by Django 4.2 on 2023-07-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_wesparating_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalrating',
            name='games',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
