# Generated by Django 4.2 on 2023-08-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20230716_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unrated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=3)),
                ('last', models.CharField(max_length=20)),
            ],
        ),
        migrations.RunSQL("CREATE INDEX idx_unrated_name_trgm ON ratings_unrated USING gist (name gist_trgm_ops);",
                          "DROP INDEX IF EXISTS idx_national_name_trgm;"),
    ]
