# Generated by Django 4.2 on 2023-08-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_unrated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unrated',
            name='country',
        ),
        migrations.RemoveField(
            model_name='unrated',
            name='last',
        ),
    ]
